In [202]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0


## Intro to Tensors

### Creating Tensors

In [203]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [204]:
# but I wanted that number '3' not like 'tensor(3)'

scalar.item()  # .item() method to get the python number from a tensor containing a single value

3

In [205]:
# dim of an scalar
scalar.ndim

0

In [206]:
print(f"Hence an Scalar has {scalar.ndim} dimension.")

Hence an Scalar has 0 dimension.


In [207]:
#  vector

vector = torch.tensor([11, 14, 1])
vector

tensor([11, 14,  1])

In [208]:
# Again i wanted that number '11' and '2' not like 'tensor([11,  2])'

ls = vector.tolist()  # .tolist() method to get the python list from a tensor containing multiple values
print(f"Vector as list: {ls}")
# or 

np_array = vector.numpy()  # .numpy() method to get the numpy array from a tensor containing multiple values
print(f"Vector as numpy array: {np_array}, Array contains no comma.")

# or

vector[0].item()  # .item() method to get the python number from a tensor containing a single value
vector[1].item()  # .item() method to get the python number from a tensor containing a single value


Vector as list: [11, 14, 1]
Vector as numpy array: [11 14  1], Array contains no comma.


14

In [209]:
for i in range(len(vector)):
    print(vector[i].item())

11
14
1


In [210]:
# one thing to see
vector.ndim

1

In [211]:
print(f"Hence a Vector has {vector.ndim} dimension.")

Hence a Vector has 1 dimension.


**Well those Square Bracket counts specify the number of the dim**

In [212]:
# BUT
print(f"Vector shape: {vector.shape}")
# number of elements in the vector
print(f"Number of elements in the vector: {vector.numel()}")


Vector shape: torch.Size([3])
Number of elements in the vector: 3


In [213]:
# MATRIX

MATRIX = torch.tensor([[-2, -1, 0],
                       [1, 2, 3],
                       [4, 5, 6]])

MATRIX

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [214]:
print(f"Hence a Matrix:\n {MATRIX.numpy()}")

Hence a Matrix:
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [215]:
MATRIX.ndim

2

In [216]:
MATRIX.shape

torch.Size([3, 3])

In [217]:
MATRIX[1]

tensor([1, 2, 3])

In [218]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [4, 5, 6],
                        [7, 8, 9],
                        [7, 8, 9]],
                            [[10, 11, 12],
                            [13, 14, 15],
                            [16, 17, 18],
                            [7, 8, 9]],
                                [[19, 20, 21],
                                [22, 23, 24],
                                [25, 26, 27],
                                [7, 8, 9]]])    

In [219]:
TENSOR.numpy()


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [ 7,  8,  9]]])

In [220]:
TENSOR.ndim

3

In [221]:
TENSOR.shape

torch.Size([3, 4, 3])

In [222]:
TENSOR[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]])

In [223]:
TENSOR[0][0] # dim = 1

tensor([1, 2, 3])

In [224]:
TENSOR[0][0][0] # dim = 2

tensor(1)

### Random Tensors !

In [225]:
# Create random tensor of size (3, 4)
# random_tensor = torch.rand(size=(3, 4), dtype=torch.float32, requires_grad=True, generator=torch.manual_seed(42), out=None, layout=torch.strided, device=None, pin_memory=False, )  # set random seed for reproducibility

random_tensor = torch.rand(size=(3, 4))  # set random seed for reproducibility
random_tensor

tensor([[0.8898, 0.7466, 0.7481, 0.5066],
        [0.6237, 0.4942, 0.6044, 0.1677],
        [0.8181, 0.4905, 0.2156, 0.9054]])

In [226]:
random_tensor.ndim

2

In [227]:
# similar to image size tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))  # H, W, C (height, width, color channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [228]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [229]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [230]:
ones.dtype # default dtype is float32

torch.float32

### Creating a range of tensors and tensors-like

In [231]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1.5)
one_to_ten
# returns 1-D range of numbers from  ceil((end-start)/step) 
# Step is added to the start value until it reaches the end

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

In [232]:
np.ceil((11-1)/1.5)

7.0

In [233]:
one_to_ten.size()

torch.Size([7])

In [234]:
# tensor - like

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros


tensor([0., 0., 0., 0., 0., 0., 0.])

In [235]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1., 1., 1., 1., 1., 1., 1.])

### Tensor data types

In [236]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,
                               device=None,
                               requires_grad=False 
# requires_grad is used to track the gradients of the tensor during backpropagation
                               )
float_32_tensor.dtype


torch.float32

In [237]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

Conversion

In [238]:
# or
new_float_16_tensor = float_32_tensor.type(torch.float16)
new_float_16_tensor.dtype

torch.float16

OR

In [239]:
new2_float_16_tensor = float_32_tensor.to(torch.float16)
new2_float_16_tensor.dtype

torch.float16

In [240]:
float_64_tensor = torch.tensor([111.0, 222.0, 333.0], dtype=torch.float64)

In [241]:
n = (float_16_tensor * float_32_tensor * float_64_tensor)

In [242]:
n.dtype

torch.float64

### Some tensor

In [243]:
some_tensor = torch.rand(3,3)
some_tensor 

tensor([[0.5031, 0.6761, 0.1601],
        [0.6391, 0.9494, 0.1955],
        [0.7299, 0.5509, 0.9718]])

In [244]:
print(f"some_tensor: \n{some_tensor},\ndtype: {some_tensor.dtype},\nshape: {some_tensor.shape},\nndim: {some_tensor.ndim},\ndevice: {some_tensor.device}")

some_tensor: 
tensor([[0.5031, 0.6761, 0.1601],
        [0.6391, 0.9494, 0.1955],
        [0.7299, 0.5509, 0.9718]]),
dtype: torch.float32,
shape: torch.Size([3, 3]),
ndim: 2,
device: cpu


### Tensor Operations

#### Elementwise

In [245]:
tensor = torch.tensor([1, 2, 3])

In [246]:
tensor + 10

tensor([11, 12, 13])

In [247]:
tensor - 1

tensor([0, 1, 2])

In [248]:
tensor * 10

tensor([10, 20, 30])

In [249]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

OR

In [250]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [251]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [252]:
torch.sub(tensor, 1)

tensor([0, 1, 2])

In [253]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix Multiplication

***Rules***:
1. `(3, 2) @ (3, 2)` ❌
2. `(2, 3) @ (3, 2)` ✅ -> `(2, 2)`
3. `(3, 2) @ (2, 3)` ✅ -> `(3, 3)`


In [254]:
print("Element-wise multiplication:\n",tensor, "*", tensor, "=", tensor * tensor)

Element-wise multiplication:
 tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [255]:
print("matrix multiplication:\n",tensor, "@", tensor, "=", tensor @ tensor)

matrix multiplication:
 tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


or

In [256]:
print("matrix multiplication:\n",tensor, "@", tensor, "=", torch.matmul(tensor, tensor))

matrix multiplication:
 tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


#### Difference between these

In [257]:
%%time

value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]


CPU times: user 65 μs, sys: 3 μs, total: 68 μs
Wall time: 69.1 μs


In [258]:
%%time
tensor @ tensor


CPU times: user 23 μs, sys: 2 μs, total: 25 μs
Wall time: 26 μs


tensor(14)

In [259]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 172 μs, sys: 57 μs, total: 229 μs
Wall time: 213 μs


tensor(14)

`matmul()` 29.1 μs < `@` 37 μs < `for loop` 193 μs

***Recommended To Use:*** 
`torch.matmul()`

#### Shape Errors in Deep Learning

In [260]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


# torch.mm(tensor_A, tensor_B)  # torch.mm() is used for matrix multiplication of 2-D tensors only. It will throw an error if the input tensors are not 2-D.



In [261]:
# torch.matmul(tensor_A, tensor_B)
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

original shapes:

In [262]:
tensor_A.shape ,  tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

original matrix

In [263]:
tensor_A ,  tensor_B

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

for matrix multiplication:

In [264]:
tensor_A, tensor_B.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

the compatiable size for the matrix multiplication:

In [265]:
tensor_A.shape ,  tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

matrix multiplication result:

In [266]:
torch.matmul(tensor_A, tensor_B.T)  # Transpose tensor_B to make it compatible for matrix multiplication

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

its shape:

In [267]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding min, max, mean, sum etc(tensor aggregation)

In [268]:
# create a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [269]:
# min value of the tensor
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [270]:
# max value of the tensor
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [271]:
# mean value of the tensor

# torch.mean(x)

# ---------------------------------------------------------------------------
# RuntimeError                              Traceback (most recent call last)
# Cell In[78], line 2
#       1 # mean value of the tensor
# ----> 2 torch.mean(x)

# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

Above error states at the end, that:

`Got: Long` which is actually `float64` or the `Double-precision floating-point format`

but we can update it to the `Single-precision floating-point format` which is actually `float32`

In [272]:

# Convert the tensor to float32 before calculating the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [273]:
# sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding positional min and max

In [274]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [275]:
x.argmin(), x.argmax() # indices of the minimum and maximum values

(tensor(0), tensor(9))

In [276]:
# so
x[x.argmin()], x[x.argmax()] # values of the minimum and maximum values

(tensor(0), tensor(90))

## Reshaping, stacking, squeezing, unsqeezing tensors

- Reshape
- View
- Stack
- Squeeze
- Unsqueeze
- Permute

***torch.reshape***

In [277]:
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [278]:
# Add an extra dim
# x_reshaped = x.reshape(1, 7) # shape should be multipe of the original input size


x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

***torch.view***

In [279]:
# change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

***View***: Changing z changes x. Cause they share the same memory!!

In [280]:
z[:, 0] = 5
z, x, z == x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[True, True, True, True, True, True, True, True, True]]))

In [281]:
# x[0] = 1
# x, z

***torch.stack***
https://docs.pytorch.org/docs/2.11/generated/torch.stack.html

In [282]:
# Stack tensors on top of eachother

x_stacked = torch.stack(
    [x, x, x, x],
    dim = 0,     
    # dim = 0 or -2 : Horizontal
    # dim = 1 or -1 : Vertical
)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

***Squeeze*** : Returns tensor with all the dimensions of input of size 1 removed

https://docs.pytorch.org/docs/2.11/generated/torch.squeeze.html



In [283]:
x_reshaped.shape

torch.Size([1, 9])

In [284]:
x_reshaped.shape

torch.Size([1, 9])

Apply the squeeze function to remove the `1` dimension from x_reshaped

In [285]:
torch.squeeze(x_reshaped, 0) ,torch.squeeze(x_reshaped, 0).shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [286]:
x_reshaped.shape

torch.Size([1, 9])

Since we had, 1x9, and applied the dim = 0 we got the 1 removed,

In [287]:
torch.squeeze(x_reshaped, 1) , torch.squeeze(x_reshaped, 1).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

So better way is also:

In [288]:
torch.squeeze(x_reshaped, (1,0)) , torch.squeeze(x_reshaped, (1,0)).shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [289]:
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# remove extra dimensions

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


***Unsqueeze***
https://docs.pytorch.org/docs/2.11/generated/torch.unsqueeze.html

In [290]:
# torch.unsqueeze() - adds a single dimension

In [291]:
print(f"Previous Tensor: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# adds extra dimensions

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)  # add the `1` at the 0th index dimension

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


***torch.permute***: https://docs.pytorch.org/docs/2.11/generated/torch.permute.html

Rearrange the dimensions in a specific order!!

In [292]:
x_original = torch.rand(size=(224, 224, 3)) # H W C channels

# permute the tensor to rearrage the axis

# convert from the HWC -> CWH
x_permuted = x_original.permute(2,0,1)
# shifts the 0->1, 1->2, 2->0
# x_original.shape, x_permuted.shape

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")


previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


**Exercise:**

In [293]:
x_original[0, 0, 0] 

tensor(0.5370)

In [294]:
x_original[0, 0, 0] = 99999

In [295]:
x_permuted[0,0,0]

tensor(99999.)