In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0


## Intro to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [3]:
# but I wanted that number '3' not like 'tensor(3)'

scalar.item()  # .item() method to get the python number from a tensor containing a single value

3

In [4]:
# dim of an scalar
scalar.ndim

0

In [5]:
print(f"Hence an Scalar has {scalar.ndim} dimension.")

Hence an Scalar has 0 dimension.


In [6]:
#  vector

vector = torch.tensor([11, 14, 1])
vector

tensor([11, 14,  1])

In [7]:
# Again i wanted that number '11' and '2' not like 'tensor([11,  2])'

ls = vector.tolist()  # .tolist() method to get the python list from a tensor containing multiple values
print(f"Vector as list: {ls}")
# or 

np_array = vector.numpy()  # .numpy() method to get the numpy array from a tensor containing multiple values
print(f"Vector as numpy array: {np_array}, Array contains no comma.")

# or

vector[0].item()  # .item() method to get the python number from a tensor containing a single value
vector[1].item()  # .item() method to get the python number from a tensor containing a single value


Vector as list: [11, 14, 1]
Vector as numpy array: [11 14  1], Array contains no comma.


14

In [8]:
for i in range(len(vector)):
    print(vector[i].item())

11
14
1


In [9]:
# one thing to see
vector.ndim

1

In [10]:
print(f"Hence a Vector has {vector.ndim} dimension.")

Hence a Vector has 1 dimension.


**Well those Square Bracket counts specify the number of the dim**

In [11]:
# BUT
print(f"Vector shape: {vector.shape}")
# number of elements in the vector
print(f"Number of elements in the vector: {vector.numel()}")


Vector shape: torch.Size([3])
Number of elements in the vector: 3


In [12]:
# MATRIX

MATRIX = torch.tensor([[-2, -1, 0],
                       [1, 2, 3],
                       [4, 5, 6]])

MATRIX

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [13]:
print(f"Hence a Matrix:\n {MATRIX.numpy()}")

Hence a Matrix:
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([3, 3])

In [16]:
MATRIX[1]

tensor([1, 2, 3])

In [17]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [4, 5, 6],
                        [7, 8, 9],
                        [7, 8, 9]],
                            [[10, 11, 12],
                            [13, 14, 15],
                            [16, 17, 18],
                            [7, 8, 9]],
                                [[19, 20, 21],
                                [22, 23, 24],
                                [25, 26, 27],
                                [7, 8, 9]]])    

In [18]:
TENSOR.numpy()


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [ 7,  8,  9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([3, 4, 3])

In [21]:
TENSOR[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]])

In [22]:
TENSOR[0][0] # dim = 1

tensor([1, 2, 3])

In [23]:
TENSOR[0][0][0] # dim = 2

tensor(1)

### Random Tensors !

In [24]:
# Create random tensor of size (3, 4)
# random_tensor = torch.rand(size=(3, 4), dtype=torch.float32, requires_grad=True, generator=torch.manual_seed(42), out=None, layout=torch.strided, device=None, pin_memory=False, )  # set random seed for reproducibility

random_tensor = torch.rand(size=(3, 4))  # set random seed for reproducibility
random_tensor

tensor([[0.2666, 0.1105, 0.2604, 0.4104],
        [0.9971, 0.4502, 0.9849, 0.7137],
        [0.2685, 0.6376, 0.5081, 0.1781]])

In [25]:
random_tensor.ndim

2

In [26]:
# similar to image size tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))  # H, W, C (height, width, color channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [28]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype # default dtype is float32

torch.float32