In [78]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0


## Intro to Tensors

### Creating Tensors

In [79]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [80]:
# but I wanted that number '3' not like 'tensor(3)'

scalar.item()  # .item() method to get the python number from a tensor containing a single value

3

In [81]:
# dim of an scalar
scalar.ndim

0

In [82]:
print(f"Hence an Scalar has {scalar.ndim} dimension.")

Hence an Scalar has 0 dimension.


In [83]:
#  vector

vector = torch.tensor([11, 14, 1])
vector

tensor([11, 14,  1])

In [84]:
# Again i wanted that number '11' and '2' not like 'tensor([11,  2])'

ls = vector.tolist()  # .tolist() method to get the python list from a tensor containing multiple values
print(f"Vector as list: {ls}")
# or 

np_array = vector.numpy()  # .numpy() method to get the numpy array from a tensor containing multiple values
print(f"Vector as numpy array: {np_array}, Array contains no comma.")

# or

vector[0].item()  # .item() method to get the python number from a tensor containing a single value
vector[1].item()  # .item() method to get the python number from a tensor containing a single value


Vector as list: [11, 14, 1]
Vector as numpy array: [11 14  1], Array contains no comma.


14

In [85]:
for i in range(len(vector)):
    print(vector[i].item())

11
14
1


In [86]:
# one thing to see
vector.ndim

1

In [87]:
print(f"Hence a Vector has {vector.ndim} dimension.")

Hence a Vector has 1 dimension.


**Well those Square Bracket counts specify the number of the dim**

In [88]:
# BUT
print(f"Vector shape: {vector.shape}")
# number of elements in the vector
print(f"Number of elements in the vector: {vector.numel()}")


Vector shape: torch.Size([3])
Number of elements in the vector: 3


In [89]:
# MATRIX

MATRIX = torch.tensor([[-2, -1, 0],
                       [1, 2, 3],
                       [4, 5, 6]])

MATRIX

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [90]:
print(f"Hence a Matrix:\n {MATRIX.numpy()}")

Hence a Matrix:
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [91]:
MATRIX.ndim

2

In [92]:
MATRIX.shape

torch.Size([3, 3])

In [93]:
MATRIX[1]

tensor([1, 2, 3])

In [94]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [4, 5, 6],
                        [7, 8, 9],
                        [7, 8, 9]],
                            [[10, 11, 12],
                            [13, 14, 15],
                            [16, 17, 18],
                            [7, 8, 9]],
                                [[19, 20, 21],
                                [22, 23, 24],
                                [25, 26, 27],
                                [7, 8, 9]]])    

In [95]:
TENSOR.numpy()


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [ 7,  8,  9]]])

In [96]:
TENSOR.ndim

3

In [97]:
TENSOR.shape

torch.Size([3, 4, 3])

In [98]:
TENSOR[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]])

In [99]:
TENSOR[0][0] # dim = 1

tensor([1, 2, 3])

In [100]:
TENSOR[0][0][0] # dim = 2

tensor(1)

### Random Tensors !

In [101]:
# Create random tensor of size (3, 4)
# random_tensor = torch.rand(size=(3, 4), dtype=torch.float32, requires_grad=True, generator=torch.manual_seed(42), out=None, layout=torch.strided, device=None, pin_memory=False, )  # set random seed for reproducibility

random_tensor = torch.rand(size=(3, 4))  # set random seed for reproducibility
random_tensor

tensor([[0.7653, 0.8588, 0.6607, 0.2888],
        [0.3490, 0.1771, 0.6013, 0.9596],
        [0.5679, 0.8104, 0.6578, 0.7756]])

In [102]:
random_tensor.ndim

2

In [103]:
# similar to image size tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))  # H, W, C (height, width, color channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [104]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [105]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
ones.dtype # default dtype is float32

torch.float32

### Creating a range of tensors and tensors-like

In [107]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1.5)
one_to_ten
# returns 1-D range of numbers from  ceil((end-start)/step) 
# Step is added to the start value until it reaches the end

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

In [108]:
np.ceil((11-1)/1.5)

7.0

In [109]:
one_to_ten.size()

torch.Size([7])

In [110]:
# tensor - like

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros


tensor([0., 0., 0., 0., 0., 0., 0.])

In [111]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1., 1., 1., 1., 1., 1., 1.])

### Tensor data types

In [112]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,
                               device=None,
                               requires_grad=False 
# requires_grad is used to track the gradients of the tensor during backpropagation
                               )
float_32_tensor.dtype


torch.float32

In [113]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

Conversion

In [114]:
# or
new_float_16_tensor = float_32_tensor.type(torch.float16)
new_float_16_tensor.dtype

torch.float16

OR

In [115]:
new2_float_16_tensor = float_32_tensor.to(torch.float16)
new2_float_16_tensor.dtype

torch.float16

In [119]:
float_64_tensor = torch.tensor([111.0, 222.0, 333.0], dtype=torch.float64)

In [120]:
n = (float_16_tensor * float_32_tensor * float_64_tensor)

In [121]:
n.dtype

torch.float64

### Some tensor

In [134]:
some_tensor = torch.rand(3,3)
some_tensor 

tensor([[0.4501, 0.7176, 0.2650],
        [0.4804, 0.4599, 0.1568],
        [0.4557, 0.5393, 0.0347]])

In [136]:
print(f"some_tensor: \n{some_tensor},\ndtype: {some_tensor.dtype},\nshape: {some_tensor.shape},\nndim: {some_tensor.ndim},\ndevice: {some_tensor.device}")

some_tensor: 
tensor([[0.4501, 0.7176, 0.2650],
        [0.4804, 0.4599, 0.1568],
        [0.4557, 0.5393, 0.0347]]),
dtype: torch.float32,
shape: torch.Size([3, 3]),
ndim: 2,
device: cpu
