In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0


## Intro to Tensors

### Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [4]:
# but I wanted that number '3' not like 'tensor(3)'

scalar.item()  # .item() method to get the python number from a tensor containing a single value

3

In [5]:
# dim of an scalar
scalar.ndim

0

In [6]:
print(f"Hence an Scalar has {scalar.ndim} dimension.")

Hence an Scalar has 0 dimension.


In [7]:
#  vector

vector = torch.tensor([11, 14, 1])
vector

tensor([11, 14,  1])

In [8]:
# Again i wanted that number '11' and '2' not like 'tensor([11,  2])'

ls = vector.tolist()  # .tolist() method to get the python list from a tensor containing multiple values
print(f"Vector as list: {ls}")
# or 

np_array = vector.numpy()  # .numpy() method to get the numpy array from a tensor containing multiple values
print(f"Vector as numpy array: {np_array}, Array contains no comma.")

# or

vector[0].item()  # .item() method to get the python number from a tensor containing a single value
vector[1].item()  # .item() method to get the python number from a tensor containing a single value


Vector as list: [11, 14, 1]
Vector as numpy array: [11 14  1], Array contains no comma.


14

In [9]:
for i in range(len(vector)):
    print(vector[i].item())

11
14
1


In [10]:
# one thing to see
vector.ndim

1

In [11]:
print(f"Hence a Vector has {vector.ndim} dimension.")

Hence a Vector has 1 dimension.


**Well those Square Bracket counts specify the number of the dim**

In [12]:
# BUT
print(f"Vector shape: {vector.shape}")
# number of elements in the vector
print(f"Number of elements in the vector: {vector.numel()}")


Vector shape: torch.Size([3])
Number of elements in the vector: 3


In [13]:
# MATRIX

MATRIX = torch.tensor([[-2, -1, 0],
                       [1, 2, 3],
                       [4, 5, 6]])

MATRIX

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [14]:
print(f"Hence a Matrix:\n {MATRIX.numpy()}")

Hence a Matrix:
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([3, 3])

In [17]:
MATRIX[1]

tensor([1, 2, 3])

In [18]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [4, 5, 6],
                        [7, 8, 9],
                        [7, 8, 9]],
                            [[10, 11, 12],
                            [13, 14, 15],
                            [16, 17, 18],
                            [7, 8, 9]],
                                [[19, 20, 21],
                                [22, 23, 24],
                                [25, 26, 27],
                                [7, 8, 9]]])    

In [19]:
TENSOR.numpy()


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [ 7,  8,  9]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([3, 4, 3])

In [22]:
TENSOR[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]])

In [23]:
TENSOR[0][0] # dim = 1

tensor([1, 2, 3])

In [24]:
TENSOR[0][0][0] # dim = 2

tensor(1)

### Random Tensors !

In [25]:
# Create random tensor of size (3, 4)
# random_tensor = torch.rand(size=(3, 4), dtype=torch.float32, requires_grad=True, generator=torch.manual_seed(42), out=None, layout=torch.strided, device=None, pin_memory=False, )  # set random seed for reproducibility

random_tensor = torch.rand(size=(3, 4))  # set random seed for reproducibility
random_tensor

tensor([[3.6250e-01, 5.7506e-02, 3.8151e-01, 6.9921e-01],
        [7.3290e-01, 6.6025e-01, 1.1674e-01, 3.2771e-04],
        [4.1525e-01, 6.2247e-01, 2.3662e-01, 5.8291e-01]])

In [26]:
random_tensor.ndim

2

In [27]:
# similar to image size tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))  # H, W, C (height, width, color channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [28]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype # default dtype is float32

torch.float32

### Creating a range of tensors and tensors-like

In [31]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1.5)
one_to_ten
# returns 1-D range of numbers from  ceil((end-start)/step) 
# Step is added to the start value until it reaches the end

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

In [32]:
np.ceil((11-1)/1.5)

7.0

In [33]:
one_to_ten.size()

torch.Size([7])

In [34]:
# tensor - like

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros


tensor([0., 0., 0., 0., 0., 0., 0.])

In [35]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1., 1., 1., 1., 1., 1., 1.])

### Tensor data types

In [36]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,
                               device=None,
                               requires_grad=False 
# requires_grad is used to track the gradients of the tensor during backpropagation
                               )
float_32_tensor.dtype


torch.float32

In [37]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

Conversion

In [38]:
# or
new_float_16_tensor = float_32_tensor.type(torch.float16)
new_float_16_tensor.dtype

torch.float16

OR

In [39]:
new2_float_16_tensor = float_32_tensor.to(torch.float16)
new2_float_16_tensor.dtype

torch.float16

In [40]:
float_64_tensor = torch.tensor([111.0, 222.0, 333.0], dtype=torch.float64)

In [41]:
n = (float_16_tensor * float_32_tensor * float_64_tensor)

In [42]:
n.dtype

torch.float64

### Some tensor

In [43]:
some_tensor = torch.rand(3,3)
some_tensor 

tensor([[0.8419, 0.8127, 0.6802],
        [0.6804, 0.9597, 0.4104],
        [0.6914, 0.5329, 0.9763]])

In [44]:
print(f"some_tensor: \n{some_tensor},\ndtype: {some_tensor.dtype},\nshape: {some_tensor.shape},\nndim: {some_tensor.ndim},\ndevice: {some_tensor.device}")

some_tensor: 
tensor([[0.8419, 0.8127, 0.6802],
        [0.6804, 0.9597, 0.4104],
        [0.6914, 0.5329, 0.9763]]),
dtype: torch.float32,
shape: torch.Size([3, 3]),
ndim: 2,
device: cpu


### Tensor Operations

#### Elementwise

In [45]:
tensor = torch.tensor([1, 2, 3])

In [46]:
tensor + 10

tensor([11, 12, 13])

In [47]:
tensor - 1

tensor([0, 1, 2])

In [48]:
tensor * 10

tensor([10, 20, 30])

In [49]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

OR

In [50]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [51]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [52]:
torch.sub(tensor, 1)

tensor([0, 1, 2])

In [53]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix Multiplication

***Rules***:
1. `(3, 2) @ (3, 2)` ❌
2. `(2, 3) @ (3, 2)` ✅ -> `(2, 2)`
3. `(3, 2) @ (2, 3)` ✅ -> `(3, 3)`


In [54]:
print("Element-wise multiplication:\n",tensor, "*", tensor, "=", tensor * tensor)

Element-wise multiplication:
 tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [55]:
print("matrix multiplication:\n",tensor, "@", tensor, "=", tensor @ tensor)

matrix multiplication:
 tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


or

In [56]:
print("matrix multiplication:\n",tensor, "@", tensor, "=", torch.matmul(tensor, tensor))

matrix multiplication:
 tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


#### Difference between these

In [57]:
%%time

value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]


CPU times: user 255 μs, sys: 706 μs, total: 961 μs
Wall time: 881 μs


In [58]:
%%time
tensor @ tensor


CPU times: user 47 μs, sys: 14 μs, total: 61 μs
Wall time: 56 μs


tensor(14)

In [59]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 48 μs, sys: 11 μs, total: 59 μs
Wall time: 53.9 μs


tensor(14)

`matmul()` 29.1 μs < `@` 37 μs < `for loop` 193 μs

***Recommended To Use:*** 
`torch.matmul()`

#### Shape Errors in Deep Learning

In [62]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


# torch.mm(tensor_A, tensor_B)  # torch.mm() is used for matrix multiplication of 2-D tensors only. It will throw an error if the input tensors are not 2-D.



In [63]:
# torch.matmul(tensor_A, tensor_B)
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

original shapes:

In [64]:
tensor_A.shape ,  tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

original matrix

In [67]:
tensor_A ,  tensor_B

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

for matrix multiplication:

In [66]:
tensor_A, tensor_B.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

the compatiable size for the matrix multiplication:

In [68]:
tensor_A.shape ,  tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

matrix multiplication result:

In [65]:
torch.matmul(tensor_A, tensor_B.T)  # Transpose tensor_B to make it compatible for matrix multiplication

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

its shape:

In [69]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])